import { Spot } from "./types";

export const spots: Spot[] = [
  // Dining
  {
    id: "maison-flora",
    name: "Maison Flora",
    category: "dining",
    neighborhood: "Design District",
    city: "Miami",
    description:
      "An intimate dining room with a seasonal tasting menu that draws from coastal Mediterranean and Japanese traditions. Omakase-style service, natural wine list, impeccable attention to detail.",
    address: "140 NE 39th St, Miami, FL 33137",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1918,
    lat: 25.8126,
    hours: "Tue–Sat 6:00 PM – 11:00 PM · Closed Sun–Mon",
    phone: "+1 (305) 555-0142",
    website: "https://maisonflora.com",
    instagram: "@maisonflora",
    priceRange: "$$$$",
    dressCode: "Smart casual",
    reservations: "Required — book via Resy, 30 days out",
    parking: "Valet available on NE 39th St · Street parking limited",
    bookingUrl: "https://resy.com/cities/mia/maison-flora",
    bookingPlatform: "Resy",
    menuUrl: "https://maisonflora.com/menu",
    events: [
      { name: "Winemaker's Dinner", date: "2026-04-12", description: "Five-course pairing with Domaine de la Romanée-Conti" },
      { name: "Chef's Table Omakase", date: "2026-04-19", description: "Ten-seat counter experience with guest chef from Tokyo" },
    ],
    tags: ["Tasting menu", "Natural wine", "Date night", "Special occasion"],
  },
  {
    id: "côte-sud",
    name: "Côte Sud",
    category: "dining",
    neighborhood: "South Beach",
    city: "Miami",
    description:
      "French-inflected seafood in a serene oceanfront setting. The raw bar is among the best in the city — pristine oysters, crudo, and a caviar service worth every dollar.",
    address: "321 Ocean Dr, Miami Beach, FL 33139",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1301,
    lat: 25.7825,
    hours: "Mon–Sun 12:00 PM – 11:00 PM",
    phone: "+1 (305) 555-0198",
    website: "https://cotesudmiami.com",
    instagram: "@cotesudmia",
    priceRange: "$$$$",
    dressCode: "Resort elegant",
    reservations: "Recommended — book via OpenTable",
    parking: "Valet at entrance · Public garage on 3rd St",
    bookingUrl: "https://opentable.com/cote-sud-miami",
    bookingPlatform: "OpenTable",
    menuUrl: "https://cotesudmiami.com/menu",
    events: [
      { name: "Sunday Jazz Brunch", date: "2026-04-06", description: "Live jazz trio with champagne and raw bar" },
    ],
    tags: ["Seafood", "Raw bar", "Oceanfront", "Brunch"],
  },
  {
    id: "nori-omakase",
    name: "Nori Omakase",
    category: "dining",
    neighborhood: "Brickell",
    city: "Miami",
    description:
      "A twelve-seat counter serving a meticulous twenty-course omakase. The fish is flown in daily from Tsukiji. Reservations open thirty days out and disappear within minutes.",
    address: "801 Brickell Ave, Miami, FL 33131",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1912,
    lat: 25.7631,
    hours: "Wed–Mon 6:00 PM – 10:00 PM · Closed Tue",
    phone: "+1 (305) 555-0267",
    website: "https://noriomakase.com",
    instagram: "@noriomakase",
    priceRange: "$$$$",
    dressCode: "Smart casual",
    reservations: "Required — book via Resy, 30 days out",
    parking: "Valet at Brickell City Centre · Street metered parking",
    bookingUrl: "https://resy.com/cities/mia/nori-omakase",
    bookingPlatform: "Resy",
    menuUrl: "https://noriomakase.com/omakase",
    tags: ["Omakase", "Sushi", "Counter dining", "Special occasion"],
  },

  // Drinks
  {
    id: "velvet-room",
    name: "Velvet Room",
    category: "drinks",
    neighborhood: "Wynwood",
    city: "Miami",
    description:
      "A dimly lit cocktail den behind an unmarked door. The bartenders work with house-made tinctures and rare spirits. No menu — tell them what you like and trust the process.",
    address: "2550 NW 2nd Ave, Miami, FL 33127",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1998,
    lat: 25.8016,
    hours: "Thu–Sat 8:00 PM – 2:00 AM · Closed Sun–Wed",
    phone: "+1 (305) 555-0334",
    website: "https://velvetroommiami.com",
    instagram: "@velvetroommia",
    priceRange: "$$$",
    dressCode: "All black encouraged",
    reservations: "Walk-in only — arrive before 9 PM for best chance",
    parking: "Street parking on NW 2nd Ave · Lot on 26th St",
    tags: ["Speakeasy", "Craft cocktails", "Late night", "No menu"],
  },
  {
    id: "apertura",
    name: "Apertura",
    category: "drinks",
    neighborhood: "Coral Gables",
    city: "Miami",
    description:
      "An elegant aperitivo bar modeled after the grand cafés of Milan. Negroni variations, a curated amaro collection, and complimentary cicchetti during golden hour.",
    address: "260 Miracle Mile, Coral Gables, FL 33134",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.259,
    lat: 25.7497,
    hours: "Mon–Sun 4:00 PM – 12:00 AM",
    phone: "+1 (305) 555-0411",
    website: "https://aperturamiami.com",
    instagram: "@apertura.mia",
    priceRange: "$$$",
    dressCode: "Smart casual",
    reservations: "Recommended for groups of 4+ via Resy",
    parking: "Public garage on Galiano St · Metered street parking",
    bookingUrl: "https://resy.com/cities/mia/apertura",
    bookingPlatform: "Resy",
    menuUrl: "https://aperturamiami.com/drinks",
    events: [
      { name: "Amaro Masterclass", date: "2026-04-10", description: "Guided tasting of 12 rare Italian amari with the bar director" },
    ],
    tags: ["Aperitivo", "Negroni", "Italian", "Happy hour"],
  },
  {
    id: "club-nocturne",
    name: "Club Nocturne",
    category: "drinks",
    neighborhood: "South Beach",
    city: "Miami",
    description:
      "The city's most discerning late-night destination. World-class sound system, rotating international DJs, and a door policy that keeps the room right. Table service is an experience unto itself.",
    address: "1235 Washington Ave, Miami Beach, FL 33139",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.134,
    lat: 25.7862,
    hours: "Fri–Sat 11:00 PM – 5:00 AM",
    phone: "+1 (305) 555-0488",
    website: "https://clubnocturne.com",
    instagram: "@clubnocturne",
    priceRange: "$$$$",
    dressCode: "Upscale — no sneakers, no shorts",
    reservations: "Table reservations via DM or concierge",
    parking: "Valet on Washington Ave · Public lot on 12th St",
    tags: ["Late night", "DJs", "Table service", "Sound system"],
  },

  // Members Clubs
  {
    id: "the-commonwealth",
    name: "The Commonwealth",
    category: "members",
    neighborhood: "Brickell",
    city: "Miami",
    description:
      "A private social club spanning three floors with a rooftop pool, chef's dining room, screening room, and co-working library. The membership is vetted and the programming is world-class.",
    address: "1200 Brickell Ave, Miami, FL 33131",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1908,
    lat: 25.762,
    hours: "Mon–Sun 7:00 AM – 12:00 AM",
    phone: "+1 (305) 555-0512",
    website: "https://thecommonwealthclub.com",
    instagram: "@thecommonwealth",
    priceRange: "$$$$",
    dressCode: "Business casual minimum",
    reservations: "Members only — apply online or by referral",
    parking: "Underground garage for members · Valet available",
    tags: ["Private club", "Rooftop pool", "Co-working", "Networking"],
  },
  {
    id: "casa-privada",
    name: "Casa Privada",
    category: "members",
    neighborhood: "South Beach",
    city: "Miami",
    description:
      "An art deco mansion converted into a members-only club. Intimate salons, a cigar terrace, a curated art collection that rotates quarterly. The kind of place where introductions happen naturally.",
    address: "1500 Collins Ave, Miami Beach, FL 33139",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1325,
    lat: 25.7885,
    hours: "Tue–Sun 5:00 PM – 1:00 AM · Closed Mon",
    phone: "+1 (305) 555-0576",
    website: "https://casaprivada.com",
    instagram: "@casaprivada",
    priceRange: "$$$$",
    dressCode: "Evening attire",
    reservations: "Members only — invitation or referral required",
    parking: "Valet on Collins Ave",
    events: [
      { name: "Quarterly Art Reveal", date: "2026-04-18", description: "Private viewing of the new collection with the curator" },
    ],
    tags: ["Private club", "Art deco", "Cigar terrace", "Art collection"],
  },

  // Wellness
  {
    id: "the-temple",
    name: "The Temple",
    category: "wellness",
    neighborhood: "Edgewater",
    city: "Miami",
    description:
      "A private training facility with top-tier equipment, cold plunge pools, infrared saunas, and a roster of elite coaches. Membership is by referral only.",
    address: "480 NE 31st St, Miami, FL 33137",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.189,
    lat: 25.805,
    hours: "Mon–Fri 5:30 AM – 9:00 PM · Sat–Sun 7:00 AM – 5:00 PM",
    phone: "+1 (305) 555-0633",
    website: "https://thetemple.fit",
    instagram: "@thetemple.fit",
    priceRange: "$$$",
    reservations: "Membership by referral — classes bookable via app",
    parking: "Private lot for members · Street parking on NE 31st",
    tags: ["Training", "Cold plunge", "Sauna", "Referral only"],
  },
  {
    id: "forma-athletics",
    name: "Forma Athletics",
    category: "wellness",
    neighborhood: "Brickell",
    city: "Miami",
    description:
      "Boutique performance gym with a focus on functional movement and recovery. The space is minimal and pristine — concrete, oak, and natural light. Classes are capped at eight.",
    address: "1010 Brickell Ave, Miami, FL 33131",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1925,
    lat: 25.7598,
    hours: "Mon–Sat 6:00 AM – 8:00 PM · Sun 8:00 AM – 2:00 PM",
    phone: "+1 (305) 555-0689",
    website: "https://formaathletics.com",
    instagram: "@forma.athletics",
    priceRange: "$$$",
    reservations: "Book classes via website or app",
    bookingUrl: "https://formaathletics.com/book",
    bookingPlatform: "Website",
    parking: "Building garage with validation · Metered street",
    tags: ["Functional training", "Small classes", "Recovery", "Minimal"],
  },
  {
    id: "stillpoint",
    name: "Stillpoint",
    category: "wellness",
    neighborhood: "Design District",
    city: "Miami",
    description:
      "A recovery-focused wellness studio offering IV therapy, cryotherapy, hyperbaric chambers, and guided breathwork sessions. The space feels like a five-star clinic, not a spa.",
    address: "120 NE 40th St, Miami, FL 33137",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1922,
    lat: 25.8132,
    hours: "Mon–Sat 9:00 AM – 7:00 PM · Closed Sun",
    phone: "+1 (305) 555-0745",
    website: "https://stillpointwellness.com",
    instagram: "@stillpoint.wellness",
    priceRange: "$$$$",
    reservations: "Required — book via website",
    bookingUrl: "https://stillpointwellness.com/book",
    bookingPlatform: "Website",
    parking: "Valet available · Design District public garages",
    tags: ["Recovery", "Cryotherapy", "IV therapy", "Breathwork"],
  },

  // Coffee
  {
    id: "drift-coffee",
    name: "Drift Coffee",
    category: "coffee",
    neighborhood: "Wynwood",
    city: "Miami",
    description:
      "Single-origin pour-overs and a rotating espresso menu in a light-filled industrial space. The beans are roasted in-house weekly. Their cortado is a quiet masterpiece.",
    address: "2700 N Miami Ave, Miami, FL 33127",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1942,
    lat: 25.8005,
    hours: "Mon–Sun 7:00 AM – 5:00 PM",
    phone: "+1 (305) 555-0801",
    website: "https://driftcoffee.co",
    instagram: "@drift.coffee",
    priceRange: "$$",
    parking: "Street parking on N Miami Ave · Lot behind building",
    tags: ["Pour-over", "Single origin", "In-house roasting", "Cortado"],
  },
  {
    id: "café-lento",
    name: "Café Lento",
    category: "coffee",
    neighborhood: "Coconut Grove",
    city: "Miami",
    description:
      "A slow coffee experience in a lush garden setting. Japanese kissaten influences meet Miami warmth. The matcha latte and house-baked financiers are essential.",
    address: "3444 Main Hwy, Miami, FL 33133",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.242,
    lat: 25.7271,
    hours: "Mon–Sat 8:00 AM – 4:00 PM · Sun 9:00 AM – 3:00 PM",
    phone: "+1 (305) 555-0856",
    website: "https://cafelento.com",
    instagram: "@cafe.lento",
    priceRange: "$$",
    parking: "Free lot on Main Hwy · Street parking available",
    tags: ["Matcha", "Garden seating", "Pastries", "Slow coffee"],
  },

  // Shopping
  {
    id: "maison-ligne",
    name: "Maison Ligne",
    category: "shopping",
    neighborhood: "Design District",
    city: "Miami",
    description:
      "A carefully edited multi-brand boutique carrying European and Japanese labels. The buying is sharp — expect to find pieces here before they appear anywhere else in the city.",
    address: "110 NE 40th St, Miami, FL 33137",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1925,
    lat: 25.8135,
    hours: "Mon–Sat 11:00 AM – 7:00 PM · Sun 12:00 PM – 5:00 PM",
    phone: "+1 (305) 555-0912",
    website: "https://maisonligne.com",
    instagram: "@maisonligne",
    priceRange: "$$$$",
    parking: "Design District public garages · Valet on NE 40th",
    events: [
      { name: "SS26 Trunk Show", date: "2026-04-15", description: "Preview the spring/summer collection from Auralee and Comoli" },
    ],
    tags: ["Multi-brand", "Japanese labels", "European fashion", "Menswear"],
  },
  {
    id: "the-archive",
    name: "The Archive",
    category: "shopping",
    neighborhood: "South Beach",
    city: "Miami",
    description:
      "Curated vintage and contemporary menswear in a gallery-like space. Rare archival pieces sit alongside emerging designers. The owner's eye is unerring.",
    address: "631 Lincoln Rd, Miami Beach, FL 33139",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1372,
    lat: 25.7907,
    hours: "Mon–Sat 11:00 AM – 8:00 PM · Sun 12:00 PM – 6:00 PM",
    phone: "+1 (305) 555-0967",
    website: "https://thearchivemiami.com",
    instagram: "@thearchive.mia",
    priceRange: "$$$",
    parking: "Public garages on Lincoln Rd · Metered street parking",
    tags: ["Vintage", "Archival", "Emerging designers", "Menswear"],
  },
  {
    id: "maison-temps",
    name: "Maison Temps",
    category: "shopping",
    neighborhood: "Design District",
    city: "Miami",
    description:
      "An independent watch dealer specializing in pre-owned Patek Philippe, Audemars Piguet, and rare vintage references. Private viewing room, white-glove service, and deep horological knowledge.",
    address: "130 NE 40th St, Miami, FL 33137",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.192,
    lat: 25.8136,
    hours: "Mon–Fri 10:00 AM – 6:00 PM · Sat by appointment",
    phone: "+1 (305) 555-1023",
    website: "https://maisontemps.com",
    instagram: "@maisontemps",
    priceRange: "$$$$",
    reservations: "Appointment recommended for viewings",
    bookingUrl: "https://maisontemps.com/appointment",
    bookingPlatform: "Website",
    parking: "Design District public garages",
    tags: ["Watches", "Patek Philippe", "Audemars Piguet", "Pre-owned"],
  },
  {
    id: "oro-fino",
    name: "Oro Fino",
    category: "shopping",
    neighborhood: "Coral Gables",
    city: "Miami",
    description:
      "A third-generation jeweler crafting bespoke pieces and estate jewelry. The workshop is visible through glass — you watch your commission take shape. Nothing leaves without the founder's approval.",
    address: "350 Miracle Mile, Coral Gables, FL 33134",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.2585,
    lat: 25.7501,
    hours: "Mon–Fri 10:00 AM – 6:00 PM · Sat 11:00 AM – 4:00 PM",
    phone: "+1 (305) 555-1078",
    website: "https://orofinojewelers.com",
    instagram: "@orofino.miami",
    priceRange: "$$$$",
    reservations: "Walk-ins welcome · Private consultations by appointment",
    parking: "Public garage on Galiano St · Metered street",
    tags: ["Bespoke jewelry", "Estate pieces", "Workshop", "Third generation"],
  },
  {
    id: "galerie-blanche",
    name: "Galerie Blanche",
    category: "shopping",
    neighborhood: "Wynwood",
    city: "Miami",
    description:
      "A blue-chip gallery representing established and mid-career contemporary artists. The program is museum-quality — expect solo shows that would hold their own at any biennial.",
    address: "2600 NW 2nd Ave, Miami, FL 33127",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1995,
    lat: 25.8012,
    hours: "Tue–Sat 10:00 AM – 6:00 PM · Closed Sun–Mon",
    phone: "+1 (305) 555-1134",
    website: "https://galerieblanche.com",
    instagram: "@galerieblanche",
    priceRange: "$$$$",
    parking: "Street parking on NW 2nd Ave · Wynwood public lots",
    events: [
      { name: "Opening Reception: New Works", date: "2026-04-08", description: "Solo exhibition opening with the artist in attendance" },
    ],
    tags: ["Contemporary art", "Blue-chip", "Solo shows", "Gallery"],
  },

  // Grooming
  {
    id: "atelier-cut",
    name: "Atelier Cut",
    category: "grooming",
    neighborhood: "Brickell",
    city: "Miami",
    description:
      "A gentleman's barbershop with private suites, hot towel shaves, and a whisky menu. Appointments only — no walk-ins, no rush, no compromise.",
    address: "900 Brickell Ave, Miami, FL 33131",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1915,
    lat: 25.7645,
    hours: "Mon–Sat 9:00 AM – 7:00 PM · Closed Sun",
    phone: "+1 (305) 555-1189",
    website: "https://ateliercut.com",
    instagram: "@atelier.cut",
    priceRange: "$$$",
    reservations: "Required — book via website",
    bookingUrl: "https://ateliercut.com/book",
    bookingPlatform: "Website",
    parking: "Building garage with validation",
    tags: ["Barbershop", "Hot towel shave", "Private suites", "Whisky"],
  },
  {
    id: "mane-studio",
    name: "Mane Studio",
    category: "grooming",
    neighborhood: "Design District",
    city: "Miami",
    description:
      "An appointment-only salon where colorists and stylists trained in Paris and Tokyo work in private rooms. The consultations alone are worth the visit.",
    address: "160 NE 40th St, Miami, FL 33137",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1915,
    lat: 25.8138,
    hours: "Tue–Sat 10:00 AM – 7:00 PM · Closed Sun–Mon",
    phone: "+1 (305) 555-1245",
    website: "https://manestudio.com",
    instagram: "@mane.studio",
    priceRange: "$$$$",
    reservations: "Required — book via website or DM",
    bookingUrl: "https://manestudio.com/book",
    bookingPlatform: "Website",
    parking: "Design District public garages",
    tags: ["Salon", "Color specialist", "Private rooms", "Appointment only"],
  },

  // Hotels
  {
    id: "hotel-cielo",
    name: "Hotel Cielo",
    category: "hotels",
    neighborhood: "South Beach",
    city: "Miami",
    description:
      "A 24-room boutique hotel with interiors by a former Aman designer. No lobby — you're greeted at the door and walked to your suite. The rooftop is residents-only and perfectly quiet.",
    address: "1680 Collins Ave, Miami Beach, FL 33139",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.1318,
    lat: 25.7895,
    hours: "24/7 — check-in from 3:00 PM",
    phone: "+1 (305) 555-1301",
    website: "https://hotelcielo.com",
    instagram: "@hotelcielo",
    priceRange: "$$$$",
    reservations: "Book direct for best rate",
    bookingUrl: "https://hotelcielo.com/reservations",
    bookingPlatform: "Direct",
    parking: "Valet included with stay",
    tags: ["Boutique hotel", "Rooftop", "Aman designer", "24 rooms"],
  },
  {
    id: "the-grove-house",
    name: "The Grove House",
    category: "hotels",
    neighborhood: "Coconut Grove",
    city: "Miami",
    description:
      "A restored 1920s estate turned eight-suite hotel hidden behind a coral rock wall. Tropical gardens, a saltwater pool, and a kitchen that sources exclusively from local farms.",
    address: "3400 Devon Rd, Miami, FL 33133",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    lng: -80.2415,
    lat: 25.7268,
    hours: "24/7 — check-in from 4:00 PM",
    phone: "+1 (305) 555-1356",
    website: "https://thegrovehouse.com",
    instagram: "@thegrovehouse",
    priceRange: "$$$$",
    reservations: "Book direct — minimum 2 nights",
    bookingUrl: "https://thegrovehouse.com/book",
    bookingPlatform: "Direct",
    parking: "Private lot for guests",
    tags: ["Estate hotel", "Tropical garden", "Saltwater pool", "Farm-to-table"],
  },
];

export function getSpotsByCity(city: string): Spot[] {
  return spots.filter((s) => s.city.toLowerCase() === city.toLowerCase());
}

export function getSpotById(id: string): Spot | undefined {
  return spots.find((s) => s.id === id);
}

export function getCategories(city: string): string[] {
  const citySpots = getSpotsByCity(city);
  return [...new Set(citySpots.map((s) => s.category))];
}
